#!/bin/sh

# Sent output of a command to a file

## Format
COMMAND > FILENAME

## Format for errors
COMMAND 2> FILENAME

## list a directory to "mylist.txt"
ls > mylist.txt

## grep "foo" to "mygrep.txt"
grep "foo" * > mygrep.txt

## list a directory and send only errors to "errors.txt"
ls 2> errors.txt

## list a directory to "mylist.txt", send errors to "errors.txt"
ls > mylist.txt 2> errors.txt


# tee
## info: https://www.computerhope.com/unix/utee.htm

## list a directory on screen and save to "mylist.txt"
ls | tee mylist.txt

## grep "foo" on screen and save to "mygrep.txt"
grep "foo" * | tee mygrep.txt


# Combine different commands

## Command as variable
### Find .html files and grep it for contents "Ink is a verb", show line number & filename
grep -nH "Ink is a verb" $(find -type f -name "*.html")

## -exec ....... {} +
### Find .html files and grep it for contents "Ink is a verb" show line number & filename
find .-type -f -iname "*.html" -exec grep -i -nH "Ink is a verb" {} +

## xargs
### Find 'foo' and replace with 'bar' recursively with grep
grep -rl 'foo' * | xargs sed -i 's/foo/bar/g'
