#!/bin/sh

# Directories

## Move to directory
cd directory

## Move up a directory
cd ..

## Move to home
cd

## Move up and back to another directory
cd ../another


# Copy/move/remove

## Copy foo to bar
cp foo bar
cp -f foo bar

## Copy directory foo to directory bar (-f force overwrite, don't show errors)
cp -r foo bar
cp -rf foo bar

## Copy a file or directory to current directory
cp -r /full/path .
cp -rf /full/path .

## Move file or directory (-f force overwrite, don't show errors)
mv file destination
mv -f file destination

## Delete a file (-f force overwrite, don't show errors)
rm file
rm -f file

## Delete directory
rm -r directory
rm -rf directory


# Creating

## Create a file if it doesn't exist
touch newfilename file2 newfile3

## Create a directory
mkdir directory

## Make a directory and all "parent" directories, no questions
mkdir -p /my/entire/path/i/will/create

## Make directories one, two, and three, right here
mkdir one two three


# Link

## Create a symlink
ln -s /original/full/path /full/path/to/destination

## Create a symlink in current directory
ln -s /original/full/path .

## Create symlink, update existing links, "force" (no questions)
ln -sfn /original/full/path /full/path/to/destination


# List

# List files
## Full list (extra info for monochrome)
l

## Short list
ls

## State path
l /path/to/list
ls /path/to/list

## Reverse
l -r
ls -r

## All (include hidden)
l -a
ls -a

## Long (owner & permissions)
l -l
ls -l

## Combine options
l -a /path/to/list
ls -a /path/to/list
l -al /path/to/list
ls -al /path/to/list


# Meaning of a list (ls -l)

UUUGGGPPP (User, Group, Public)
7 	rwx   read, write, and execute
6 	rw- 	read and write
5 	r-x 	read and execute
4 	r-- 	read only
3   -wx 	write and execute
2   -w- 	write only
1 	--x 	execute only
0 	--- 	none


# Owner

## File
chown user:group file file2 file3

## Directory
chown -R user:group file file2 file3

# Permissions
## make eXecutable
chmod +x file

## make not eXecutable
chmod -x file

## make fully available to everyone
chmod 777 file

## make read/write to owner, unavaliable to public
chmod 660 file

# Edit with different editors

## In terminal
nano file
vim file

## GUI
gedit file file2
kate file file2


# Names with spaces

## These are two different files
My Stuff

## This is one file
"My Stuff"

## This will open gedit to edit "My" and "Stuff" as separate files
gedit My Stuff

## This will open gedit to edit "My Stuff"
gedit "My Stuff"

## This will delete "My"
rm My Stuff

## This will delete "My Stuff"
rm "My Stuff"

## This will copy "My" to "Stuff"
cp My Stuff My New Stuff

## This will copy "My Stuff" to "My New Stuff"
cp "My Stuff" "My New Stuff"
