#!/bin/sh

# List all current variables
printenv

# List all variables under sudo
sudo printenv

# Command variable
$0

# First variable after command
$1

# Second variable after command
$2

# Set a variable in a file to second variable after command
NEW_VARIABLE=$2

# Variables after 9 use {}
${10}

# Set a variable to a command output
NEW_VARIABLE=$(first command | next command | next command)

## Variables of variables (requires BASH)
#!/bin/bash
pear4="peeled"
NUM=4
fruit="pear${NUM}"
echo $fruit      # returns direct value of $fruit: "pear4"
echo ${!fruit}   # returns value of value, $pear4: "peeled"

